Scarthgap/rz sbc uboot
vudangRVC/meta-renesas-sst pull request #1
Opened 2024-10-02 06:46 UTC by khanh-doduy-bv

Support build U-boot on Yocto Scarthgap:
- Add recipes-bsp/trusted-firmware-a
- Add recipes-bsp/firmware-pack
- Add recipes-bsp/u-boot

2024-10-02 08:49 UTC, tiennguyenuh commented
@khanh-doduy-bv,

Please squash all commits related to U-Boot into the commit that adds the U-Boot recipes.

2024-10-02 09:04 UTC, khanh-doduy-bv commented
> @khanh-doduy-bv,
> 
> Please squash all commits related to U-Boot into the commit that adds the U-Boot recipes.

Please check it out

2024-10-06 14:30 UTC, tiennguyenuh commented on recipes-bsp/firmware-pack/bootparameter/bootparameter.c
Change `GPL-2.0+` to `GPL-2.0-or-later` with new modern SPDX license identifiers.

2024-10-06 14:30 UTC, tiennguyenuh commented on recipes-bsp/firmware-pack/bootparameter-native_1.0.bb
Change `GPLv2` to `GPL-2.0-only`  with new modern SPDX license identifiers.

2024-10-06 14:30 UTC, tiennguyenuh commented on recipes-bsp/u-boot/files/readme.txt
This `readme.txt` file is not needed since it hasn't been used anywhere

2024-10-06 14:30 UTC, tiennguyenuh commented on recipes-bsp/u-boot/u-boot-common_2021.10.inc
Change `GPLv2+` to `GPL-2.0-or-later` with new modern SPDX license identifiers.

2024-10-06 14:30 UTC, tiennguyenuh commented on recipes-bsp/u-boot/u-boot_2021.10.bb
```
require u-boot-common_${PV}.inc
require u-boot.inc
```

Instead of using local inc files, should we use these files from poky?

```
require recipes-bsp/u-boot/u-boot-common.inc
require recipes-bsp/u-boot/u-boot.inc
```

Refer to the rz community u-boot recipe: https://github.com/renesas-rz/rz-community-bsp/tree/master/meta-rz-bsp/recipes-bsp/u-boot. Their recipe appears to be clean

2024-10-06 14:37 UTC, tiennguyenuh commented on recipes-bsp/firmware-pack/bootparameter-native_1.0.bb
> +LICENSE = "GPLv2"
Change `GPLv2` to `GPL-2.0-only`  with new modern SPDX license identifiers.

2024-10-06 14:37 UTC, tiennguyenuh commented on recipes-bsp/firmware-pack/bootparameter/bootparameter.c
> +// SPDX-License-Identifier: GPL-2.0+
Change `GPL-2.0+` to `GPL-2.0-or-later` with new modern SPDX license identifiers.

2024-10-06 14:37 UTC, tiennguyenuh commented on recipes-bsp/u-boot/u-boot-common_2021.10.inc
> +LICENSE = "GPLv2+"
Change `GPLv2+` to `GPL-2.0-or-later` with new modern SPDX license identifiers.

2024-10-06 14:37 UTC, tiennguyenuh commented on recipes-bsp/u-boot/u-boot_2021.10.bb
> +require u-boot-common_${PV}.inc
```
require u-boot-common_${PV}.inc
require u-boot.inc
```

Instead of using local .inc files, should we use these files from poky?

```
require recipes-bsp/u-boot/u-boot-common.inc
require recipes-bsp/u-boot/u-boot.inc
```

Refer to the rz community u-boot recipe: https://github.com/renesas-rz/rz-community-bsp/tree/master/meta-rz-bsp/recipes-bsp/u-boot. Their recipe appears to be clean.

2024-10-07 06:27 UTC, khanh-doduy-bv commented on recipes-bsp/u-boot/files/readme.txt
removed

2024-10-07 06:27 UTC, khanh-doduy-bv commented on recipes-bsp/firmware-pack/bootparameter-native_1.0.bb
> +LICENSE = "GPLv2"
done

2024-10-07 06:27 UTC, khanh-doduy-bv commented on recipes-bsp/firmware-pack/bootparameter/bootparameter.c
> +// SPDX-License-Identifier: GPL-2.0+
done

2024-10-07 06:27 UTC, khanh-doduy-bv commented on recipes-bsp/u-boot/u-boot-common_2021.10.inc
> +LICENSE = "GPLv2+"
done

2024-10-07 06:27 UTC, khanh-doduy-bv commented on recipes-bsp/u-boot/u-boot_2021.10.bb
> +require u-boot-common_${PV}.inc
done but not testing yet

2024-10-07 07:49 UTC, tiennguyenuh commented on recipes-bsp/trusted-firmware-a/trusted-firmware-a.bb
> +SRC_URI = " \
I think we should specify a machine for BRANCH, SRC_URI and SRCREV

```
SRC_URI:rzg2l-sbc =
BRANCH:rzg2l-sbc
SRCREV_machine:rzg2l-sbc = "${AUTOREV}"
```

2024-10-07 07:49 UTC, tiennguyenuh commented on recipes-bsp/u-boot/u-boot_2021.10.bb
> +SRCREV = "${AUTOREV}"
Also this recipe

```
SRC_URI:rzg2l-sbc =
BRANCH:rzg2l-sbc
SRCREV_machine:rzg2l-sbc = "${AUTOREV}"
```

2024-10-07 07:49 UTC, tiennguyenuh commented on recipes-bsp/firmware-pack/bootparameter-native_1.0.bb
> +}
Should we add COMPATIBLE_MACHINE = "(rzg2l-sbc)" to this recipe? as this recipe create binaries in the correct format for **RZG2L board**.

2024-10-07 07:49 UTC, tiennguyenuh commented on recipes-bsp/firmware-pack/fiptool-native.bb
> +SRC_URI = "${URL};protocol=https;branch=${BRANCH}"
I think we should specify a machine for `BRANCH`, `SRC_URI`, and `SRCREV` since we plan to support multiple boards in the future.
```
SRC_URI:rzg2l-sbc =
BRANCH:rzg2l-sbc
SRCREV_machine:rzg2l-sbc = "${AUTOREV}"
```

2024-10-07 07:49 UTC, tiennguyenuh commented on recipes-bsp/firmware-pack/firmware-pack.bb
> +addtask deploy before do_build after do_compile
Should we add COMPATIBLE_MACHINE = "(rzg2l-sbc)" to this recipe?

2024-10-08 03:13 UTC, khanh-doduy-bv commented on recipes-bsp/trusted-firmware-a/trusted-firmware-a.bb
> +SRC_URI = " \
I think specifying the machine should appear in the .bbappend files, while the .bb files should be common.

2024-10-08 04:37 UTC, vudangRVC requested changes

2024-10-08 04:37 UTC, vudangRVC commented on conf/machine/rzg2l-sbc.conf
> +#UBOOT_MACHINE = "rzpi_defconfig"
Please remove this comment. It may cause confusion.

2024-10-08 04:37 UTC, vudangRVC commented on conf/machine/rzg2l-sbc.conf
> +UBOOT_CONFIG[rzg2l-sbc] = "rzpi_defconfig"
https://git.yoctoproject.org/poky/tree/meta/classes-recipe/uboot-config.bbclass#n3

Just wanted to ensure that we align to the correct definition

2024-10-08 04:37 UTC, vudangRVC commented on recipes-bsp/firmware-pack/bootparameter-native_1.0.bb
> +}
FYI, RZV2L is using this firmware flashing method as well

2024-10-08 04:37 UTC, vudangRVC commented on recipes-bsp/trusted-firmware-a/trusted-firmware-a.bb
> +SRC_URI = " \
@khanh-doduy-bv, remove a .bbappend file from a clean recipe.

2024-10-08 04:42 UTC, vudangRVC commented on recipes-bsp/trusted-firmware-a/trusted-firmware-a.bb
> +SRC_URI = " \
And we don't want to add .bbappend file in this clean recipe. The .bbappend file should be added by users

2024-10-08 07:18 UTC, khanh-doduy-bv commented on recipes-bsp/trusted-firmware-a/trusted-firmware-a.bb
> +SRC_URI = " \
done

2024-10-08 07:18 UTC, khanh-doduy-bv commented on recipes-bsp/u-boot/u-boot_2021.10.bb
> +SRCREV = "${AUTOREV}"
done

2024-10-08 07:19 UTC, khanh-doduy-bv commented on recipes-bsp/firmware-pack/fiptool-native.bb
> +SRC_URI = "${URL};protocol=https;branch=${BRANCH}"
it's native tool so we can't define COMPATIBLE_MACHINE on it, just added COMPATIBLE_MACHINE on firmware-pack.bb

2024-10-08 07:20 UTC, khanh-doduy-bv commented on recipes-bsp/firmware-pack/firmware-pack.bb
> +addtask deploy before do_build after do_compile
added

2024-10-08 07:20 UTC, khanh-doduy-bv commented on conf/machine/rzg2l-sbc.conf
> +#UBOOT_MACHINE = "rzpi_defconfig"
done

2024-10-08 07:22 UTC, khanh-doduy-bv commented on conf/machine/rzg2l-sbc.conf
> +UBOOT_CONFIG[rzg2l-sbc] = "rzpi_defconfig"
i saw it's aligned, is it ok?

2024-10-09 08:59 UTC, khanh-doduy-bv commented on recipes-bsp/flash-writer/flash-writer.bb
Hi @vudangRVC @tiennguyenuh  i've pushed a commit to support Flash Writer, please help me review it. Thank you

2024-10-09 15:10 UTC, vudangRVC commented
@khanh-doduy-bv, I think the update is okay now, just one more thing, please keep the indentation consistent.
It should be 4 spaces same as the Linux PR: https://github.com/Renesas-SST/meta-renesas/pull/19/files
For c files, it's okay to keep them as they are (tab - 8 spaces)

2024-10-09 16:16 UTC, tiennguyenuh commented
> @khanh-doduy-bv, I think the update is okay now, just one more thing, please keep the indentation consistent. It should be 4 spaces same as the Linux PR: https://github.com/Renesas-SST/meta-renesas/pull/19/files For c files, it's okay to keep them as they are (tab - 8 spaces)

Also, the commits should be consistent as well (use 4 spaces for indentation). Please check your commits and refactor them accordingly.

2024-10-10 04:53 UTC, khanh-doduy-bv commented
@tiennguyenuh  @vudangRVC   
Commits and .bb files have been formatted. Please check it again

2024-10-14 04:08 UTC, vudangRVC commented on recipes-bsp/firmware-pack/firmware-pack.bb
> +        if [ "${PMIC_SUPPORT}" = "1" ]; then
Correct the indentation here

2024-10-14 04:12 UTC, vudangRVC reviewed
Fix the indentation error that I pointed out. Then, this PR is okay. Let's wait for the Linux PR to be merged.

2024-10-14 04:21 UTC, khanh-doduy-bv commented on recipes-bsp/firmware-pack/firmware-pack.bb
> +        if [ "${PMIC_SUPPORT}" = "1" ]; then
done

2024-10-22 08:51 UTC, closed without merging